---
version: 1
disable_existing_loggers: false
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default

formatters:
  default:
    format: '%(asctime)s %(levelname)s %(name)s:%(lineno)d %(request_id)s %(message)s'

loggers: 
  '':
    handlers: [console]
    level: DEBUG
    propagate: true